/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUploadJdRouteImport } from './routes/app.upload-jd'
import { Route as AppScheduleRouteImport } from './routes/app.schedule'
import { Route as AppResumeMatchRouteImport } from './routes/app.resume-match'
import { Route as AppPrepareRouteImport } from './routes/app.prepare'
import { Route as AppPerformanceRouteImport } from './routes/app.performance'
import { Route as AppMcqRouteImport } from './routes/app.mcq'
import { Route as AppCodingRouteImport } from './routes/app.coding'
import { Route as AppChatRouteImport } from './routes/app.chat'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadJdRoute = AppUploadJdRouteImport.update({
  id: '/upload-jd',
  path: '/upload-jd',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppResumeMatchRoute = AppResumeMatchRouteImport.update({
  id: '/resume-match',
  path: '/resume-match',
  getParentRoute: () => AppRoute,
} as any)
const AppPrepareRoute = AppPrepareRouteImport.update({
  id: '/prepare',
  path: '/prepare',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppMcqRoute = AppMcqRouteImport.update({
  id: '/mcq',
  path: '/mcq',
  getParentRoute: () => AppRoute,
} as any)
const AppCodingRoute = AppCodingRouteImport.update({
  id: '/coding',
  path: '/coding',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/chat': typeof AppChatRoute
  '/app/coding': typeof AppCodingRoute
  '/app/mcq': typeof AppMcqRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/prepare': typeof AppPrepareRoute
  '/app/resume-match': typeof AppResumeMatchRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/upload-jd': typeof AppUploadJdRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/chat': typeof AppChatRoute
  '/app/coding': typeof AppCodingRoute
  '/app/mcq': typeof AppMcqRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/prepare': typeof AppPrepareRoute
  '/app/resume-match': typeof AppResumeMatchRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/upload-jd': typeof AppUploadJdRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/chat': typeof AppChatRoute
  '/app/coding': typeof AppCodingRoute
  '/app/mcq': typeof AppMcqRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/prepare': typeof AppPrepareRoute
  '/app/resume-match': typeof AppResumeMatchRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/upload-jd': typeof AppUploadJdRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/chat'
    | '/app/coding'
    | '/app/mcq'
    | '/app/performance'
    | '/app/prepare'
    | '/app/resume-match'
    | '/app/schedule'
    | '/app/upload-jd'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/chat'
    | '/app/coding'
    | '/app/mcq'
    | '/app/performance'
    | '/app/prepare'
    | '/app/resume-match'
    | '/app/schedule'
    | '/app/upload-jd'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/chat'
    | '/app/coding'
    | '/app/mcq'
    | '/app/performance'
    | '/app/prepare'
    | '/app/resume-match'
    | '/app/schedule'
    | '/app/upload-jd'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/upload-jd': {
      id: '/app/upload-jd'
      path: '/upload-jd'
      fullPath: '/app/upload-jd'
      preLoaderRoute: typeof AppUploadJdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/schedule': {
      id: '/app/schedule'
      path: '/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resume-match': {
      id: '/app/resume-match'
      path: '/resume-match'
      fullPath: '/app/resume-match'
      preLoaderRoute: typeof AppResumeMatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/prepare': {
      id: '/app/prepare'
      path: '/prepare'
      fullPath: '/app/prepare'
      preLoaderRoute: typeof AppPrepareRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/performance': {
      id: '/app/performance'
      path: '/performance'
      fullPath: '/app/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mcq': {
      id: '/app/mcq'
      path: '/mcq'
      fullPath: '/app/mcq'
      preLoaderRoute: typeof AppMcqRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coding': {
      id: '/app/coding'
      path: '/coding'
      fullPath: '/app/coding'
      preLoaderRoute: typeof AppCodingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppCodingRoute: typeof AppCodingRoute
  AppMcqRoute: typeof AppMcqRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppPrepareRoute: typeof AppPrepareRoute
  AppResumeMatchRoute: typeof AppResumeMatchRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppUploadJdRoute: typeof AppUploadJdRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppCodingRoute: AppCodingRoute,
  AppMcqRoute: AppMcqRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppPrepareRoute: AppPrepareRoute,
  AppResumeMatchRoute: AppResumeMatchRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppUploadJdRoute: AppUploadJdRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
